import { afterEach, describe, expect, it, vi } from 'vitest'
import { chmodSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { createHash, generateKeyPairSync, sign } from 'node:crypto'
import { preflightReady } from '../src/lib/commands.js'
import { controllerCanonicalJson } from '../src/lib/controller-provenance.js'

const keys=generateKeyPairSync('ed25519')
const publicKey=keys.publicKey.export({type:'spki',format:'pem'}).toString()
const keyId=`controller-ed25519:${createHash('sha256').update(publicKey).digest('base64url')}`
const roots:string[]=[]
afterEach(()=>{vi.restoreAllMocks();delete process.env.LOOPCTL_TRUSTED_CONTROLLER_KEYS_FILE;delete process.env.LOOPCTL_BOT_PREFLIGHT_CONFIG;while(roots.length)rmSync(roots.pop()!,{recursive:true,force:true})})
function signed(value:Record<string,unknown>){const unsigned={...value,controllerSignatureAlgorithm:'ed25519',controllerKeyId:keyId,controllerPublicKey:publicKey};const withDigest={...unsigned,packetDigest:createHash('sha256').update(controllerCanonicalJson(unsigned)).digest('hex')};return {...withDigest,controllerSignature:sign(null,Buffer.from(controllerCanonicalJson(withDigest)),keys.privateKey).toString('base64')}}
function packet(overrides:Record<string,unknown>={}){return signed({...{kind:'preflight_attempt',schema:'loopctl-action-packet-v1',actionId:'action-1',actionKey:'action-key-1',action:{id:'action-1',key:'action-key-1',kind:'preflight_attempt',state:'ready',workItemRevision:2,targetPrincipal:'catsco-user:559',targetTopicId:'grp_42',targetDigest:'target-digest'},workItemId:'wi-1',workItemRevision:2,targetPrincipal:'catsco-user:559',targetTopicId:'grp_42',targetDigest:'target-digest',contracts:{taskContractHash:'task-contract',referenceSnapshotHash:'reference-snapshot',writeScopeHash:'write-scope',acceptanceContractHash:'acceptance-contract'},ownerUid:'602',loopId:'loop-1',profileId:'profile-1',catscoProjectId:'81',workerTopicId:'grp_42',evidenceTopicId:'grp_43',workerSessionId:'session:v2:catscompany:group:grp_42:agent:559',githubRepo:'org/repo',writeScope:['src'],attemptId:'attempt-1',attemptNumber:1,generation:0,runtimePrincipal:'catsco-user:559',leaseExpiresAt:'2030-01-01T00:00:00.000Z',proofMode:'catsco-message',workBundle:{contractDigest:'bundle-digest',instructions:'preflight only',deliverables:['readiness']}},...overrides})}
function install(root:string,{botUid='559',apiKey='cc_secret_do_not_log',url='https://app.catsco.cc',controllerUid='602'}={}){const pins=join(root,'pins.json');writeFileSync(pins,JSON.stringify({version:1,keys:[{ownerUid:'602',controllerKeyId:keyId,publicKey}]}));chmodSync(pins,0o600);process.env.LOOPCTL_TRUSTED_CONTROLLER_KEYS_FILE=pins;const key=join(root,'bot.key');writeFileSync(key,apiKey);chmodSync(key,0o600);const config=join(root,'bot.json');writeFileSync(config,JSON.stringify({version:1,transport:'catsco-bot-preflight-v1',httpBaseUrl:url,expectedBotUid:botUid,controllerUid,apiKeyFile:key}));chmodSync(config,0o600);process.env.LOOPCTL_BOT_PREFLIGHT_CONFIG=config;return {key,config,apiKey}}
function response(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}})}
function nativeRow(value:unknown,overrides:Record<string,unknown>={}){return {id:8,seq_id:8,topic_id:'grp_42',from_uid:602,type:'text',msg_type:'text',actor_uid:602,content:value,...overrides}}
function botRow(content='worker planning chatter',overrides:Record<string,unknown>={}){return {id:9,seq_id:9,topic_id:'grp_42',from_uid:559,type:'text',msg_type:'text',content,...overrides}}
function receipt(id:number|string,content:string){return {messages:[{id,seq_id:id,topic_id:'grp_43',from_uid:559,type:'worker_ready',content:JSON.parse(content)}]}}
function nativeFetch(row:unknown){let content='';let sent=false;const fetch=vi.fn(async(url:string,init:RequestInit={})=>{if(url.endsWith('/api/me'))return response({uid:'559',account_type:'bot'});if(url.includes('topic_id=grp_42'))return response(row&&typeof row==='object'&&!Array.isArray(row)&&Array.isArray((row as {messages?:unknown}).messages)?row:{messages:[row]});if(url.includes('topic_id=grp_43'))return response(receipt(9,content));if(url.endsWith('/api/messages/send')){sent=true;const body=JSON.parse(String(init.body));content=body.content;return response({id:9,seq_id:9,topic_id:'grp_43',from_uid:559,client_msg_id:body.client_msg_id,duplicate:false})}throw new Error(`unexpected ${url}`)});return {fetch,sent:()=>sent}}
function root(){const value=mkdtempSync(join(tmpdir(),'preflight-bot-'));roots.push(value);return value}

describe('preflight-ready native Bot source',()=>{
 it('reads exactly one native Action and emits canonical Bot evidence without a packet file',async()=>{const dir=root();const {apiKey}=install(dir);const mock=nativeFetch(nativeRow(packet()));vi.stubGlobal('fetch',mock.fetch);const result=await preflightReady({'received-topic':'grp_42'});expect(result.targetTopicId).toBe('grp_43');expect(result.event).toMatchObject({type:'worker_ready',source:'catsco-user:559'});expect(mock.fetch).toHaveBeenCalledTimes(5);expect(String(mock.fetch.mock.calls[1][0])).toContain('topic_id=grp_42');expect(String(mock.fetch.mock.calls[1][0])).toContain('latest=true');expect(String(mock.fetch.mock.calls[1][0])).toContain('limit=100');expect(JSON.stringify(result)).not.toContain(apiKey);expect(mock.sent()).toBe(true)})
 it('selects the Controller Action despite Worker Bot chatter written after it',async()=>{const dir=root();install(dir);const mock=nativeFetch({messages:[nativeRow(packet()),botRow(),botRow('tool output',{id:10,seq_id:10})]});vi.stubGlobal('fetch',mock.fetch);const result=await preflightReady({'received-topic':'grp_42'});expect(result.event.type).toBe('worker_ready');expect(mock.sent()).toBe(true)})
 it('rejects history with only Worker Bot chatter and sends no evidence',async()=>{const dir=root();install(dir);const mock=nativeFetch({messages:[botRow(),botRow('tool output',{id:10,seq_id:10})]});vi.stubGlobal('fetch',mock.fetch);await expect(preflightReady({'received-topic':'grp_42'})).rejects.toThrow('found 0 eligible');expect(mock.sent()).toBe(false)})
 it('rejects packet-file rather than accepting an LLM-created local packet',async()=>{const dir=root();install(dir);const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await expect(preflightReady({'received-topic':'grp_42','packet-file':'packet.json'})).rejects.toThrow('packet-file is not supported');expect(fetch).not.toHaveBeenCalled()})
 it('rejects a signed packet whose owner is not configured Controller before evidence send',async()=>{const dir=root();install(dir);const mock=nativeFetch(nativeRow(packet({ownerUid:'999'})));vi.stubGlobal('fetch',mock.fetch);await expect(preflightReady({'received-topic':'grp_42'})).rejects.toThrow('ownerUid');expect(mock.sent()).toBe(false)})
 it.each([
  ['cardinality',{messages:[]}],['topic', {messages:[nativeRow(packet(),{topic_id:'grp_99'})]}],['sender',{messages:[nativeRow(packet(),{from_uid:999})]}],['from alias',{messages:[nativeRow(packet(),{from_uid:undefined,from:'usr999'})]}],['type',{messages:[nativeRow(packet(),{type:'worker_ready'})]}],['msg_type',{messages:[nativeRow(packet(),{msg_type:'worker_ready'})]}],['id',{messages:[nativeRow(packet(),{id:'bad'})]}],['sequence',{messages:[nativeRow(packet(),{seq_id:9})]}],['content',{messages:[nativeRow('{bad json')]}],['actor',{messages:[nativeRow(packet(),{actor_uid:999})]}]
 ])('rejects native source %s with no evidence send',async(_label,source)=>{const dir=root();install(dir);let sent=false;const fetch=vi.fn(async(url:string,init:RequestInit={})=>{if(url.endsWith('/api/me'))return response({uid:'559',account_type:'bot'});if(url.includes('topic_id=grp_42'))return response(source);if(url.endsWith('/api/messages/send'))sent=true;return response({messages:[]})});vi.stubGlobal('fetch',fetch);await expect(preflightReady({'received-topic':'grp_42'})).rejects.toThrow();expect(sent).toBe(false)})
 it('rejects multiple valid Controller Actions with no evidence send',async()=>{const dir=root();install(dir);let sent=false;const fetch=vi.fn(async(url:string)=>{if(url.endsWith('/api/me'))return response({uid:'559',account_type:'bot'});if(url.includes('topic_id=grp_42'))return response({messages:[nativeRow(packet()),botRow(),nativeRow(packet(),{id:10,seq_id:10})]});if(url.endsWith('/api/messages/send'))sent=true;return response({messages:[]})});vi.stubGlobal('fetch',fetch);await expect(preflightReady({'received-topic':'grp_42'})).rejects.toThrow('found 2 eligible');expect(sent).toBe(false)})
 it('rejects unsafe Bot configuration before any HTTP request',async()=>{const dir=root();const {key,apiKey}=install(dir);chmodSync(key,0o644);const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await expect(preflightReady({'received-topic':'grp_42'})).rejects.toThrow('mode 0600');expect(String(await preflightReady({'received-topic':'grp_42'}).catch(e=>e))).not.toContain(apiKey);expect(fetch).not.toHaveBeenCalled()})
 it('rejects symlinked Bot config before any HTTP request',async()=>{const dir=root();const {config}=install(dir);rmSync(config);symlinkSync('bot.key',config);const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await expect(preflightReady({'received-topic':'grp_42'})).rejects.toThrow('regular file');expect(fetch).not.toHaveBeenCalled()})
})
